import sharp from 'sharp';
import {test,expect} from '../helpers/fixtures';
import {loadDoc,setTool,clickPage,flushInput} from '../canvas/helpers';
import {getDocument} from '../helpers/app-state';
import {snap} from '../helpers/screenshot';

test.use({open:null});
test('native preedit paints glyphs, updates, cancels, commits and undoes once',async({galley},info)=>{
  const {page}=galley;
  await loadDoc(page,{frames:[{id:'ime',type:'text',x:36,y:36,w:220,h:100,text:''},{id:'other',type:'text',x:36,y:180,w:220,h:80,text:'Other story stays visible.'}]});
  await page.evaluate(()=>{const g=(window as any).__galley,s=g.store.getState(),doc=structuredClone(s.history.doc.stories.story_ime.doc);
    doc.content[0].attrs.overrides={print:{fontSize:24,leading:36}};
    s.dispatch(g.model.setStoryDoc,{storyId:'story_ime',doc});s.dispatch(g.model.setFrameProps,{ids:['ime'],props:{inset:12}});});
  await page.waitForSelector('.galley-page[data-ready=true]');
  await setTool(page,'type');await clickPage(page,{x:60,y:60});await expect(page.getByTestId('text-editor')).toBeFocused();
  await page.addStyleTag({content:'.gl-text-editor {caret-color:transparent!important}'});
  const before=(await getDocument(page)).stories.story_ime.doc;
  const frame=page.locator('.galley-page .galley-text[data-frame-id=ime]');
  const box=(await frame.boundingBox())!;
  const clip={x:Math.ceil(box.x+3),y:Math.ceil(box.y+2),width:Math.floor(box.width-6),height:Math.floor(box.height-4)};
  const pixels=async()=>sharp(await page.screenshot({clip,caret:'hide'})).removeAlpha().raw().toBuffer();
  const blank=await pixels();
  await page.evaluate(()=>{const e=(window as any).__galleyText.editor;(window as any).__imeView=e.view;(window as any).__imeParagraph=e.view.dom.querySelector('p');});
  const c=await page.context().newCDPSession(page);
  const counts:number[]=[];
  for(const text of ['に','日本']) {
    await c.send('Input.imeSetComposition',{text,selectionStart:text.length,selectionEnd:text.length});await flushInput(page);
    expect((await getDocument(page)).stories.story_ime.doc).toEqual(before);
    // Inspect the middle of the actual native glyph box: an underline or caret alone cannot pass this check.
    const glyph=await page.evaluate(()=>{const p=document.querySelector('[data-testid=text-editor] p')!,r=document.createRange();r.selectNodeContents(p);const b=r.getBoundingClientRect();return {x:b.x+2,y:b.y+b.height*.2,width:Math.max(1,b.width-4),height:b.height*.5};});
    const ink=await sharp(await page.screenshot({clip:glyph,caret:'hide'})).removeAlpha().raw().toBuffer();
    const count=Array.from({length:ink.length/3},(_,i)=>Math.max(ink[i*3],ink[i*3+1],ink[i*3+2])<180).filter(Boolean).length;
    counts.push(count);await snap(page,`ime-preedit-${text==='に'?'kana':'japanese'}`,{testInfo:info});
    expect(count,'native glyph ink inside the preedit box').toBeGreaterThan(12);
    expect(await page.evaluate(()=>{const e=(window as any).__galleyText.editor;return e.view===(window as any).__imeView && e.view.dom.querySelector('p')===(window as any).__imeParagraph;})).toBe(true);
    await expect(frame).toHaveCSS('visibility','hidden');
    await expect(page.locator('.galley-text[data-frame-id=other]')).toHaveCSS('visibility','visible');
  }
  expect(counts[1]).toBeGreaterThan(counts[0]);
  await c.send('Input.imeSetComposition',{text:'',selectionStart:0,selectionEnd:0});
  await page.waitForFunction(()=>{const e=(window as any).__galleyText.editor;return !e.composing && !e.pendingRethread && !e.view.dom.hasAttribute('data-composition-paint');});await flushInput(page);
  expect((await getDocument(page)).stories.story_ime.doc).toEqual(before);await expect(frame).toHaveCSS('visibility','visible');
  expect(await pixels()).toEqual(blank);await snap(page,'ime-preedit-cancelled',{testInfo:info});
  await c.send('Input.imeSetComposition',{text:'日本',selectionStart:2,selectionEnd:2});await c.send('Input.insertText',{text:'日本'});
  await page.waitForFunction(()=>{const e=(window as any).__galleyText.editor;return !e.composing && !e.pendingRethread && !e.view.dom.hasAttribute('data-composition-paint');});await flushInput(page);
  expect((await getDocument(page)).stories.story_ime.doc.content[0].content).toEqual([{type:'text',text:'日本'}]);
  await expect(frame).toHaveCSS('visibility','visible');await expect(frame).toHaveText('日本');
  expect(await pixels()).not.toEqual(blank);await snap(page,'ime-preedit-committed',{testInfo:info});
  await page.keyboard.press('Meta+z');await flushInput(page);
  expect((await getDocument(page)).stories.story_ime.doc).toEqual(before);expect(await pixels()).toEqual(blank);
  await snap(page,'ime-preedit-undone',{testInfo:info});
  console.log(`Native preedit glyph pixels kana=${counts[0]} Japanese=${counts[1]}; cancellation/one undo restore exact blank pixels.`);
});

test('preedit uses live proofed ink without replacing native DOM or painting the old story twice',async({galley},info)=>{
  const {page}=galley;
  await loadDoc(page,{frames:[{id:'ime',type:'text',x:36,y:36,w:220,h:100,text:'OLD'},{id:'reference',type:'text',x:36,y:180,w:220,h:100,text:'日本'}]});
  await page.evaluate(()=>{const g=(window as any).__galley,s=g.store.getState();
    s.dispatch(g.model.addSwatch,{swatch:{id:'ime_ink',name:'Composition ink',type:'cmyk',values:[0,100,0,0]}});
    for(const id of ['ime','reference']){const doc=structuredClone(s.history.doc.stories[`story_${id}`].doc);doc.content[0].attrs.overrides={shared:{fill:g.model.paint('ime_ink')},print:{fontSize:24,leading:36}};
      s.dispatch(g.model.setStoryDoc,{storyId:`story_${id}`,doc});s.dispatch(g.model.setFrameProps,{ids:[id],props:{inset:12}});}});
  await page.waitForSelector('.galley-page[data-ready=true]');
  await setTool(page,'type');await clickPage(page,{x:60,y:60});
  const before=(await getDocument(page)).stories.story_ime.doc;
  await page.evaluate(()=>{const e=(window as any).__galleyText.editor;e.setStorySelection(4);e.view.focus();(window as any).__imeView=e.view;});
  const c=await page.context().newCDPSession(page);
  await c.send('Input.imeSetComposition',{text:'日本',selectionStart:2,selectionEnd:2});
  const paragraph=await page.evaluateHandle(()=>document.querySelector('[data-testid=text-editor] p'));
  const first=await page.locator('[data-testid=text-editor] p').evaluate(p=>getComputedStyle(p).color);
  await page.evaluate(()=>{const g=(window as any).__galley;g.store.getState().dispatch(g.model.setSwatchProps,{id:'ime_ink',props:{values:[100,0,0,0]}});});
  await page.waitForSelector('.galley-page[data-ready=true]');await flushInput(page);
  const color=await page.locator('[data-testid=text-editor] p').evaluate(p=>getComputedStyle(p).color);
  expect(color).not.toBe(first);
  expect(color).toBe(await page.locator('.galley-text[data-frame-id=reference] p').evaluate(p=>getComputedStyle(p).color));
  expect((await getDocument(page)).stories.story_ime.doc).toEqual(before);
  expect(await page.evaluate(p=>{const e=(window as any).__galleyText.editor;return e.composing && e.view===(window as any).__imeView && e.view.dom.querySelector('p')===p;},paragraph)).toBe(true);
  await expect(page.locator('.galley-text[data-frame-id=ime]')).toHaveCSS('visibility','hidden');
  await expect(page.locator('.galley-text[data-frame-id=reference]')).toHaveCSS('visibility','visible');
  const bounds=await page.locator('[data-testid=text-editor] p').evaluate(p=>{const r=document.createRange();r.selectNodeContents(p);const b=r.getBoundingClientRect();return {x:b.x+2,y:b.y+b.height*.2,width:b.width-4,height:b.height*.5};});
  const ink=await sharp(await page.screenshot({clip:bounds,caret:'hide'})).removeAlpha().raw().toBuffer();
  const rgb=color.match(/\d+/g)!.map(Number);
  const matching=Array.from({length:ink.length/3},(_,i)=>rgb.every((v,j)=>Math.abs(ink[i*3+j]-v)<=3)).filter(Boolean).length;
  expect(matching,'actual preedit glyph pixels match the settled ICC proof color').toBeGreaterThan(12);
  await snap(page,'ime-preedit-proof-color',{testInfo:info});
  await c.send('Input.imeSetComposition',{text:'',selectionStart:0,selectionEnd:0});
  await page.waitForFunction(()=>!(window as any).__galleyText.editor.view.dom.hasAttribute('data-composition-paint'));
  await expect(page.locator('.galley-text[data-frame-id=ime]')).toHaveCSS('visibility','visible');await expect(page.locator('.galley-text[data-frame-id=ime]')).toHaveText('OLD');
  expect((await getDocument(page)).stories.story_ime.doc).toEqual(before);
  console.log(`Proof color ${color}: ${matching} actual matching glyph pixels; same native view/paragraph, old source retained.`);
});
