import {test,expect} from '../helpers/fixtures';
import {getDocument,getDocumentJson,runCommand} from '../helpers/app-state';
import {snap} from '../helpers/screenshot';
import {clickPage,setTool} from '../canvas/helpers';
import {textFixture} from './helpers';
test.use({open:null});
test('ports link into a chain, frame click links, unlink and undo preserve the source story',async({galley},info)=>{
  const {page}=galley;await textFixture(page,false,1600);
  const port=(id:string,end:string)=>page.locator(`[data-text-port="${end}"][data-frame-id="${id}"]`);
  const source=(await getDocument(page)).stories.story_t1.doc;
  await expect(page.locator('[data-testid=overset-count][data-frame-id=t1]')).toContainText('overset words');
  await port('t1','out').click();
  await expect(page.getByTestId('text-threads')).toHaveAttribute('data-linking-from','t1');
  await port('t2','in').click();
  let doc=await getDocument(page);expect(doc.stories.story_t1.frameIds).toEqual(['t1','t2']);expect(doc.frames.t2.storyId).toBe('story_t1');
  await expect(page.locator('.galley-text[data-frame-id=t2]')).not.toHaveText('');
  await port('t2','out').click();await clickPage(page,{x:350,y:280});
  doc=await getDocument(page);expect(doc.stories.story_t1.frameIds).toEqual(['t1','t2','t3']);expect(doc.stories.story_t1.doc).toEqual(source);
  await runCommand(page,'view.showTextThreads');
  await expect(page.locator('[data-testid=thread-lines] [data-thread-from]')).toHaveCount(2);
  await snap(page,'thread-ports-and-overset',{testInfo:info});
  const linked=await getDocumentJson(page);
  await port('t2','in').click();doc=await getDocument(page);
  expect(doc.stories.story_t1.frameIds).toEqual(['t1']);expect(doc.stories.story_t1.doc).toEqual(source);
  expect(doc.frames.t2.storyId).not.toBe('story_t1');expect(doc.stories[doc.frames.t2.storyId].frameIds).toEqual(['t2','t3']);
  await page.keyboard.press('Meta+z');expect(await getDocumentJson(page)).toBe(linked);
  await expect(page.locator('[data-testid=thread-lines] [data-thread-from]')).toHaveCount(2);
  await runCommand(page,'view.showTextThreads');await expect(page.getByTestId('thread-lines')).toHaveCount(0);
});
test('Type caret selection and pending formatting are shared with the controls without changing the story first',async({galley},info)=>{
  const {page}=galley;await textFixture(page,true,800);await setTool(page,'type');
  await clickPage(page,{x:60,y:242});
  const editor=page.getByTestId('text-editor');await expect(editor).toBeFocused();
  const state=await page.evaluate(()=>{const g=(window as any).__galley,e=(window as any).__galleyText.editor;return {selection:g.store.getState().textSelection,first:e.res.slots[1].start};});
  expect(state.selection.storyId).toBe('story_t1');expect(state.selection.head).toBeGreaterThanOrEqual(state.first);
  const before=await getDocumentJson(page);
  const handled=await page.evaluate(()=>{
    (window as any).__pendingCaret=null;window.addEventListener('galley:caret-state',(e:any)=>(window as any).__pendingCaret=e.detail);
    const detail={kind:'overrides',patch:{set:{shared:{fontWeight:800}}},handled:false};window.dispatchEvent(new CustomEvent('galley:caret-format',{detail}));return {handled:detail.handled,pending:(window as any).__pendingCaret};
  });
  expect(handled.handled).toBe(true);expect(handled.pending.marks).toContainEqual({type:'override',attrs:{shared:{fontWeight:800},print:null,web:null}});
  expect(await getDocumentJson(page)).toBe(before);
  await page.keyboard.type('BOLD');
  const doc=await getDocument(page);expect(JSON.stringify(doc.stories.story_t1.doc)).toContain('"fontWeight":800');
  const sel=await page.evaluate(()=>{const e=(window as any).__galleyText.editor;e.setStorySelection(e.res.slots[0].end-25,e.res.slots[1].start+35,0);return (window as any).__galley.store.getState().textSelection;});
  expect(sel.head).toBeGreaterThan(sel.anchor);await snap(page,'cross-frame-selection',{testInfo:info});
  await page.keyboard.press('Escape');await expect(editor).toHaveCount(0);
  expect(await page.evaluate(()=>(window as any).__galley.store.getState().textSelection)).toBeNull();
});
