/**
 * Builds the `poster-basic` fixture document with the model's own commands, so it is valid by construction and
 * exercises the same code paths the editor does. The poster follows docs/plans/assets/phases-1-2/editor-phase1.svg:
 * Tabloid, an orange CMYK block running into the bleed, a Studio Blue CMYK headline, 100K black body text, a
 * PANTONE 185 C spot ellipse with white text, and a photo (generated by generate-photo.ts).
 *
 * Text frame origins and sizes are multiples of 3 pt and leadings multiples of 0.75 pt (whole CSS pixels), the
 * conditions under which the Phase 0 spikes measured exact line positions. P1-04 (lane A) measures the rest.
 */
import {
  addAsset,
  addFrame,
  addGuide,
  addSwatch,
  applyCommand,
  createDocument,
  createHistory,
  createStory,
  inches,
  paint,
  SWATCH_BLACK,
  SWATCH_PAPER,
  type Frame,
  type GalleyDocument,
  type HistoryState,
  type Id,
  type Swatch,
  type TextAttrs,
} from '@galley/model';

export const POSTER_ENGINE_VERSION = '44.5.1';

export interface PosterPhoto {
  /** Path inside the package, relative. */
  path: string;
  hash: string;
  width: number;
  height: number;
}

const LAYER = 'layer_1';
const PAGE = 'page_1';

function text(h: HistoryState, id: Id, body: string, box: { x: number; y: number; w: number; h: number }, style: Partial<TextAttrs>): HistoryState {
  const frame: Frame = {
    id,
    type: 'text',
    name: '',
    layerId: LAYER,
    ...box,
    rotation: 0,
    fill: null,
    stroke: null,
    storyId: `story_${id}`,
    inset: 0,
  };
  return applyCommand(h, addFrame, { frame, pageId: PAGE, story: createStory(`story_${id}`, body, style) });
}

export function buildPosterBasic(photo: PosterPhoto): GalleyDocument {
  let h = createHistory(
    createDocument({
      title: 'Spring Poster',
      engineVersion: POSTER_ENGINE_VERSION,
      page: {
        id: PAGE,
        width: inches(11),
        height: inches(17),
        margins: 36,
        columns: { count: 3, gutter: 12 },
        bleed: inches(0.125),
        slug: inches(0.5),
      },
      layer: { id: LAYER, name: 'Layer 1' },
    }),
  );

  const swatches: Swatch[] = [
    { id: 'warm-orange', name: 'Warm Orange', type: 'cmyk', values: [0, 60, 100, 0] },
    { id: 'studio-blue', name: 'Studio Blue', type: 'cmyk', values: [100, 80, 0, 20] },
    { id: 'pms-185-c', name: 'PANTONE 185 C', type: 'spot', values: [0, 91, 76, 0] },
    { id: 'teal', name: 'Teal', type: 'cmyk', values: [85, 10, 40, 10] },
  ];
  for (const swatch of swatches) h = applyCommand(h, addSwatch, { swatch });

  const black = paint(SWATCH_BLACK);

  // 1. orange block, from the top bleed edge to y = 465, bleeding off the left and right
  h = applyCommand(h, addFrame, {
    frame: { id: 'orange-block', type: 'rect', name: 'Orange block', layerId: LAYER, x: -9, y: -9, w: 810, h: 474, rotation: 0, fill: paint('warm-orange'), stroke: null },
    pageId: PAGE,
  });

  // 2-4. headline, subhead, details
  h = text(h, 'spring', 'SPRING', { x: 36, y: 72, w: 720, h: 168 }, { fontWeight: 800, fontSize: 160, leading: 168, tracking: -20, fill: paint('studio-blue') });
  h = text(h, 'open-studio', 'OPEN STUDIO', { x: 36, y: 252, w: 720, h: 78 }, { fontWeight: 800, fontSize: 70, leading: 75, tracking: -10, fill: black });
  h = text(h, 'details', 'Saturday, May 16 · 10am–4pm · 412 Grove Street', { x: 36, y: 357, w: 720, h: 30 }, { fontSize: 22.5, leading: 27, fill: black });

  // 5-6. body copy (100K black) and the web address
  h = text(
    h,
    'body',
    'Twenty studios open their doors for one day. Watch screen printing, letterpress and riso demos, browse prints, and meet the people who make them. Free entry, all ages.',
    { x: 36, y: 951, w: 444, h: 120 },
    { fontSize: 18, leading: 27, fill: black },
  );
  h = text(h, 'url', 'galleystudio.example/spring', { x: 36, y: 1074, w: 444, h: 27 }, { fontWeight: 700, fontSize: 18, leading: 27, fill: black });

  // 7-8. the PANTONE 185 C ellipse with "FREE" knocked out in [Paper]
  h = applyCommand(h, addFrame, {
    frame: { id: 'free-ellipse', type: 'ellipse', name: 'Ellipse', layerId: LAYER, x: 579, y: 945, w: 160, h: 160, rotation: 0, fill: paint('pms-185-c'), stroke: null },
    pageId: PAGE,
  });
  h = text(h, 'free', 'FREE', { x: 579, y: 1008, w: 160, h: 39 }, { fontWeight: 900, fontSize: 37.5, leading: 39, align: 'center', fill: paint(SWATCH_PAPER) });

  // 9. the photo, filling its 720 x 384 pt frame proportionally (the image is 1.875:1, like the frame)
  h = applyCommand(h, addAsset, {
    asset: { id: 'photo', kind: 'image', path: photo.path, hash: photo.hash, width: photo.width, height: photo.height, ppi: 300, colorSpace: 'rgb' },
  });
  h = applyCommand(h, addFrame, {
    frame: {
      id: 'photo-frame',
      type: 'image',
      name: 'photo.jpg',
      layerId: LAYER,
      x: 36,
      y: 516,
      w: 720,
      h: 384,
      rotation: 0,
      fill: null,
      stroke: null,
      assetId: 'photo',
      content: { x: 0, y: 0, w: 720, h: 384 },
    },
    pageId: PAGE,
  });

  // a horizontal ruler guide, as in the mockup
  h = applyCommand(h, addGuide, { guide: { id: 'guide_1', orientation: 'horizontal', position: 489, pageId: PAGE } });
  return h.doc;
}
