import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import sharp from 'sharp';
import { test, expect } from '../helpers/fixtures';
import { getDocumentJson, getEditorState, runCommand } from '../helpers/app-state';
import { FIXTURES } from '../helpers/launch';
import { getDoc, loadDoc } from '../canvas/helpers';
import { clickMenuItem, dispatchModel, getFrame, stubDialogs } from '../shell/helpers';
import { snap } from '../helpers/screenshot';

test.use({ open: null });
const temp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'galley-links-e2e-'));
const png = async (file: string, width: number, height: number, background: string) => { fs.mkdirSync(path.dirname(file), { recursive: true }); await sharp({ create: { width, height, channels: 3, background } }).withMetadata({ density: 150 }).png().toFile(file); };
const files = (page: any) => page.evaluate(() => { const g = (window as any).__galley; return g.model.serializeDocument(g.store.getState().history.doc); });

test('Links selects usages, relinks safely, retains original undo bytes across scratch Save As, and reopens replacement', async ({ galley }, testInfo) => {
  const { page, app } = galley;
  const dir = temp();
  const source = path.join(dir, 'old', 'image.png');
  const replacement = path.join(dir, 'new', 'image.png');
  await png(source, 300, 150, '#d12222'); await png(replacement, 600, 200, '#2244d1');
  await loadDoc(page);
  await dispatchModel(page, 'setMeta', { title: 'Links test' });
  await stubDialogs(app, { open: [source] });
  await page.keyboard.press('Meta+d');
  await expect.poll(async () => (await getEditorState(page)).selection.length).toBe(1);
  const frameId = (await getEditorState(page)).selection[0]!;
  await dispatchModel(page, 'setFrameProps', { ids: [frameId], props: { rotation: 25, content: { x: -10, y: -20, w: 144, h: 36 } } });
  const old = Object.values<any>((await getDoc(page)).assets)[0]!;
  await clickMenuItem(app, 'window.links');
  const row = page.locator(`[data-asset-id="${old.id}"]`);
  await expect(row).toHaveAttribute('data-status', 'ok');
  await expect(row).toContainText('Actual 150 ppi');
  await expect(row).toContainText('Effective 150 × 300 ppi');
  await row.getByTitle('Select image frame').click();
  expect((await getEditorState(page)).selection).toEqual([frameId]);
  const prior = await getDocumentJson(page);
  const steps = (await getEditorState(page)).undoSteps;
  await stubDialogs(app, {}); await row.getByRole('button', { name: 'Relink…' }).click();
  await expect.poll(async () => (await getEditorState(page)).undoSteps).toBe(steps);
  expect(await getDocumentJson(page)).toBe(prior);
  const invalid = path.join(dir, 'not-an-image.txt'); fs.writeFileSync(invalid, 'bad');
  await stubDialogs(app, { open: [invalid] }); await row.getByRole('button', { name: 'Relink…' }).click();
  await expect(page.getByTestId('links-error')).toContainText('not a PNG or JPEG');
  expect(await getDocumentJson(page)).toBe(prior);
  const truncated = path.join(dir, 'truncated.png'); fs.writeFileSync(truncated, fs.readFileSync(source).subarray(0, 50));
  await stubDialogs(app, { open: [truncated] }); await row.getByRole('button', { name: 'Relink…' }).click();
  await expect(page.getByTestId('links-error')).toContainText('not a PNG or JPEG');
  expect(await getDocumentJson(page)).toBe(prior);
  await stubDialogs(app, { open: [replacement] }); await row.getByRole('button', { name: 'Relink…' }).click();
  await expect.poll(async () => (await getEditorState(page)).undoSteps).toBe(steps + 1);
  const updated = (await getDoc(page)).assets[old.id];
  expect(updated.path).toBe('assets/image-2.png');
  expect(await getFrame(page, frameId)).toMatchObject({ rotation: 25, content: { x: -10, y: -20, w: 144, h: 36 } });
  await expect(row).toContainText('Effective 300 × 400 ppi');
  await snap(page, 'phase3-links-relinked', { testInfo });
  const saved = path.join(dir, 'relinked.galley');
  await stubDialogs(app, { save: [saved] }); await runCommand(page, 'file.saveAs');
  expect(fs.readFileSync(path.join(saved, old.path))).toEqual(fs.readFileSync(source));
  expect(fs.readFileSync(path.join(saved, updated.path))).toEqual(fs.readFileSync(replacement));
  await page.keyboard.press('Meta+z');
  expect((await getDoc(page)).assets[old.id]).toEqual(old);
  await expect(row).toHaveAttribute('data-status', 'ok');
  // Original bytes still decode after the scratch package was deleted by Save As.
  await expect.poll(async () => page.locator('.galley-image img').evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(300);
  await page.keyboard.press('Meta+Shift+z');
  await expect.poll(async () => page.locator('.galley-image img').evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(600);
  await runCommand(page, 'file.save');
  await stubDialogs(app, { open: [saved] }); await runCommand(page, 'file.open');
  expect((await getDoc(page)).assets[old.id]).toEqual(updated);
  const out = path.join(dir, 'replacement.pdf');
  await stubDialogs(app, { save: [out] });
  const result = await page.evaluate(async (files) => (window as any).galley.press.exportPdf({ files, suggestedName: 'Replacement', options: { bleed: false, marks: false } }), await files(page));
  expect(result.status).toBe('saved');
  expect(spawnSync('pdfimages', ['-list', out], { encoding: 'utf8' }).stdout).toMatch(/image\s+600\s+200/);
});

test('Check detects changed and missing packaged bytes, refreshes the canvas and repairs export', async ({ galley }, testInfo) => {
  const { page, app } = galley;
  const dir = temp(); const pkg = path.join(dir, 'poster.galley');
  fs.cpSync(FIXTURES.posterBasic, pkg, { recursive: true });
  await stubDialogs(app, { open: [pkg] }); await runCommand(page, 'file.open');
  await clickMenuItem(app, 'window.links');
  const asset = Object.values<any>((await getDoc(page)).assets)[0]!;
  const row = page.locator(`[data-asset-id="${asset.id}"]`);
  await expect(row).toHaveAttribute('data-status', 'ok');
  const replacement = path.join(dir, 'blue.png'); await png(replacement, 400, 250, '#2255cc');
  fs.copyFileSync(replacement, path.join(pkg, asset.path));
  await page.getByRole('button', { name: 'Check Links', exact: true }).click();
  await expect(row).toHaveAttribute('data-status', 'changed');
  await expect.poll(async () => page.locator('.galley-image img').evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(400);
  await snap(page, 'phase3-links-changed', { testInfo });
  fs.writeFileSync(path.join(pkg, asset.path), 'corrupt image');
  await page.getByRole('button', { name: 'Check Links', exact: true }).click();
  await expect(row).toHaveAttribute('data-status', 'unreadable');
  const corruptResult = await page.evaluate((files) => (window as any).galley.press.exportPdf({ files, suggestedName: 'Corrupt', options: { bleed: false, marks: false } }), await files(page));
  expect(corruptResult.status).toBe('error');
  fs.unlinkSync(path.join(pkg, asset.path));
  await page.getByRole('button', { name: 'Check Links', exact: true }).click();
  await expect(row).toHaveAttribute('data-status', 'missing');
  await snap(page, 'phase3-links-missing', { testInfo });
  const malformed = await page.evaluate(() => (window as any).galley.press.exportPdf({ files: { document: 'bad json' }, suggestedName: 'Bad', options: { bleed: false, marks: false } }));
  expect(malformed.status).toBe('error');
  const request = { files: await files(page), suggestedName: 'Repaired', options: { bleed: false, marks: false } };
  expect(await page.evaluate((r) => (window as any).galley.press.exportPdf(r), request)).toMatchObject({ status: 'error', message: expect.stringContaining('missing') });
  await stubDialogs(app, { open: [replacement] }); await row.getByRole('button', { name: 'Relink…' }).click();
  await expect(row).toHaveAttribute('data-status', 'ok');
  const out = path.join(dir, 'repaired.pdf'); await stubDialogs(app, { save: [out] });
  expect((await page.evaluate((r) => (window as any).galley.press.exportPdf(r), { ...request, files: await files(page) })).status).toBe('saved');
  await snap(page, 'phase3-links-repaired', { testInfo });
});

test('a delayed relink cannot copy into or mutate a different document', async ({ galley }) => {
  const { page, app } = galley;
  const dir = temp(); const source = path.join(dir, 'red.png'); await png(source, 200, 100, '#f00');
  await loadDoc(page); await stubDialogs(app, { open: [source] }); await page.keyboard.press('Meta+d');
  await expect.poll(async () => (await getEditorState(page)).selection.length).toBe(1);
  await clickMenuItem(app, 'window.links');
  await app.evaluate(({ dialog }) => { dialog.showOpenDialog = (() => new Promise((resolve) => { (globalThis as any).__resolveRelink = resolve; })) as any; });
  await page.getByRole('button', { name: 'Relink…' }).click();
  await page.evaluate(async () => { await (window as any).galley.files.newDocument(); const g = (window as any).__galley; g.store.getState().openDocument(g.model.createDocument({ title: 'Different' })); });
  await app.evaluate((_e, source) => (globalThis as any).__resolveRelink({ canceled: false, filePaths: [source] }), source);
  await expect.poll(async () => Object.keys((await getDoc(page)).assets).length).toBe(0);
  expect((await getDoc(page)).meta.title).toBe('Different');
  await expect(page.getByTestId('links-error')).toHaveCount(0);
});
