import { test, expect } from '../helpers/fixtures';
import { getDoc } from '../canvas/helpers';
import { expectBaseline, snap } from '../helpers/screenshot';
import { field, saveStyle, selectRange, specimen, styleCreate } from './helpers';
test.use({ open: null });
test('create, base, apply, redefine, clear overrides and apply/remove character styles through the panels', async ({ galley }) => {
  const { page } = galley;
  await specimen(page);
  const paraPanel = page.locator('[data-panel="paragraphStyles"]');
  await styleCreate(page, 'paragraph', 'Body First', '[Basic Paragraph]');
  let editor = page.getByTestId('paragraph-style-editor');
  await editor.getByRole('tab', { name: 'Print', exact: true }).click();
  await field(page, 'fontSize', '10', '[data-testid="paragraph-style-editor"]');
  await field(page, 'leading', '13.5', '[data-testid="paragraph-style-editor"]');
  await saveStyle(page, 'paragraph');
  await styleCreate(page, 'paragraph', 'Body', 'Body First');
  await saveStyle(page, 'paragraph');
  const doc = await getDoc(page);
  const body = Object.values(doc.paragraphStyles).find((s: any) => s.name === 'Body') as any;
  const first = Object.values(doc.paragraphStyles).find((s: any) => s.name === 'Body First') as any;
  expect(body.basedOn).toBe(first.id);
  await page.evaluate(() => (window as any).__galley.store.getState().setSelection(['a', 'b']));
  await paraPanel.locator(`[data-style-id="${body.id}"]`).click();
  await expect.poll(async () => (await getDoc(page)).stories.story_b.doc.content[0].attrs.style).toBe(body.id);
  await expect(page.locator('[data-frame-type="text"] p').first()).toHaveCSS('font-family', 'Inter, sans-serif');
  for (const id of ['a', 'b']) await expect(page.locator(`[data-frame-id="${id}"] p`).first()).toHaveCSS('font-size', '13.3333px');
  await selectRange(page);
  await field(page, 'fontSize', '12');
  await expect(paraPanel.getByTestId('paragraphStyles-override')).toBeVisible();
  await paraPanel.getByRole('button', { name: 'Redefine', exact: true }).click();
  for (const id of ['a', 'b']) await expect(page.locator(`[data-frame-id="${id}"] p`).first()).toHaveCSS('font-size', '16px');
  expect((await getDoc(page)).paragraphStyles[body.id].print.fontSize).toBe(12);
  await field(page, 'tracking', '35');
  await expect(paraPanel.getByTestId('paragraphStyles-override')).toBeVisible();
  await paraPanel.getByRole('button', { name: 'Clear Overrides', exact: true }).click();
  await expect(paraPanel.getByTestId('paragraphStyles-override')).toHaveCount(0);
  await expect(page.locator('[data-frame-id="a"] p').first()).toHaveCSS('letter-spacing', 'normal');
  await paraPanel.getByRole('button', { name: 'Edit', exact: true }).click();
  editor = page.getByTestId('paragraph-style-editor');
  await editor.getByRole('tab', { name: 'Web (read-only)', exact: true }).click();
  await expect(editor.getByText('Stored, edited in Phase 6')).toBeVisible();
  await expect(editor.locator('.gl-style-web input')).toHaveCount(0);
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click();
  await styleCreate(page, 'character', 'Emphasis', '[None]');
  editor = page.getByTestId('character-style-editor');
  await editor.locator('[data-type-control="fontStyle"]').selectOption('700:italic');
  await saveStyle(page, 'character');
  const emphasis = Object.values((await getDoc(page)).characterStyles).find((s: any) => s.name === 'Emphasis') as any;
  const charPanel = page.locator('[data-panel="characterStyles"]');
  await charPanel.locator(`[data-style-id="${emphasis.id}"]`).click();
  await expect(page.locator('[data-frame-id="a"] p').first().locator('span').first()).toHaveCSS('font-weight', '700');
  await expect(page.locator('[data-frame-id="a"] p').first().locator('span').first()).toHaveCSS('font-style', 'italic');
  expect((await getDoc(page)).stories.story_a.doc.content[0].content[0].marks[0].attrs.style).toBe(emphasis.id);
  await charPanel.locator('[data-style-id="none"]').click();
  await expect(page.locator('[data-frame-id="a"] p').first().locator('span').first()).toHaveCSS('font-style', 'normal');
  expect((await getDoc(page)).stories.story_a.doc.content[0].content[0].marks).toBeUndefined();
  await charPanel.locator('.gl-panel-header').click();
  await snap(page, 'styles-panel');
  await expectBaseline(page, 'styles-panel');
});
